import "@fortawesome/fontawesome-free/css/all.min.css"
import type { Metadata } from "next";
import  "./globals.css";
import NextAuthProvider from "./components/providers/next-auth.providers";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({

  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body
      >
        <NextAuthProvider>

        {children}
        </NextAuthProvider>
      </body>
    </html>
  );
}
